### ISSUE TITLE
导出pdf字体改变

### ISSUE THREAD

**Issue by MuttonYung** [MondayCha/Typora-Academic-Zh#2]
导出pdf后正文全部消失；
注释掉@media print{}之后
正文出现，但是是默认字体，而非华文中宋
typora中显示是正常的
<img width="749" alt="testmd1" src="https://user-images.githubusercontent.com/55025557/159617705-d2823923-13e7-4dfb-85f2-5f6736fa7649.png">
<img width="956" alt="testmd" src="https://user-images.githubusercontent.com/55025557/159617699-60c8097d-a122-448e-9453-366cb281e366.png">

**Comment by MuttonYung** [comment]
如果选择打印-Microsoft Print to PDF
是正常显示字体的

**Comment by MondayCha** [comment]
> 如果选择打印-Microsoft Print to PDF 是正常显示字体的

谢谢反馈，但我在 Typora 0.9.96 下无法复现。请问使用其他主题导出 PDF 是正常的吗（[#2411](https://github.com/typora/typora-issues/issues/2411)）？重新下载字体包能否解决问题？

**Comment by acotor** [comment]
Typora 1.2.5 Windows 10，使用本主题以导出形式生成 PDF，极大概率出现正文、列表内容为空的情况，重复多次偶尔正常。图片依次为编辑视图、导出的 PDF。
![Screenshot_2022-05-19_09-25-39_Windows](https://user-images.githubusercontent.com/22100376/169189926-d2ad18a3-0c87-45d4-aca8-1a6b87785b81.png)
![Screenshot_2022-05-19_09-26-39_Windows](https://user-images.githubusercontent.com/22100376/169189941-1612d9ed-e0d5-4b05-b869-abc7c85f0f89.png)

**Comment by MondayCha** [comment]
> Typora 1.2.5 Windows 10，使用本主题以导出形式生成 PDF，极大概率出现正文、列表内容为空的情况，重复多次偶尔正常。图片依次为编辑视图、导出的 PDF。 ![Screenshot_2022-05-19_09-25-39_Windows](https://user-images.githubusercontent.com/22100376/169189926-d2ad18a3-0c87-45d4-aca8-1a6b87785b81.png) ![Screenshot_2022-05-19_09-26-39_Windows](https://user-images.githubusercontent.com/22100376/169189941-1612d9ed-e0d5-4b05-b869-abc7c85f0f89.png)

谢谢反馈，请问是否方便进入「设置→高级设置→开启调试模式」后重启 Typora，之后进入文章正文，右键「进入调试模式」开启控制台，导出PDF文件，查看控制台是否有报错？

![image](https://user-images.githubusercontent.com/45418105/169195241-2c5ac11b-7152-4dda-9e84-e136d9c1f593.png)

**Comment by acotor** [comment]
@MondayCha 按照你的指导操作，控制台显示内容见下图。（检查了 PDF 文件，正文和列表内容依旧为空）
![Screenshot_2022-05-19_11-08-32_Windows](https://user-images.githubusercontent.com/22100376/169196154-9d25d395-0c7c-4c40-b409-3e09a5ae7bbf.png)

**Comment by MondayCha** [comment]
@acotor 好吧，我推测可能与主题使用的自定义字体有关？说不定是 Typora 依赖的 PDF-lib 的问题。由于本月在做毕设，下个月我会尝试修复，感谢协助~

**Comment by acotor** [comment]
> @acotor 好吧，我推测可能与主题使用的自定义字体有关？说不定是 Typora 依赖的 PDF-lib 的问题。由于本月在做毕设，下个月我会尝试修复，感谢协助~

谢谢。很喜欢这个主题，中宋字体在我的应用场景中很适合，很有出版品、正式交付品的风格。我会先用打印 PDF 方式替代。另外，我也发现 Typora 还可以使用第三方 PDF 引擎（目前有问题的是“导出为 PDF Typora/Webkit”选项），有时间我也尝试看看。

祝毕业顺利~

**Comment by MuttonYung** [comment]
过了好久。。。不知从何时起就正常了，
现在我这边可以正常导出，
检查了一下@media print{}目前是注释掉的，
感谢作者，这个主题真的非常漂亮，我基本上一直在用
